"""initial schema

Revision ID: 9c51d96bbecd
Revises: 
Create Date: 2025-11-06 15:40:47.568806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c51d96bbecd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_vendors_id'), 'vendors', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('style', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('product_type', sa.String(), nullable=True),
    sa.Column('pricing_unit', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('backing', sa.String(), nullable=True),
    sa.Column('retail_price', sa.Float(), nullable=True),
    sa.Column('is_promo', sa.Boolean(), nullable=True),
    sa.Column('start_promo_date', sa.String(), nullable=True),
    sa.Column('end_promo_date', sa.String(), nullable=True),
    sa.Column('promo_cut_cost', sa.Float(), nullable=True),
    sa.Column('promo_roll_cost', sa.Float(), nullable=True),
    sa.Column('is_dropped', sa.Boolean(), nullable=True),
    sa.Column('retail_formula', sa.String(), nullable=True),
    sa.Column('display_tags', sa.Boolean(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('private_style', sa.String(), nullable=True),
    sa.Column('private_color', sa.String(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('custom', sa.String(), nullable=True),
    sa.Column('style_ux', sa.String(), nullable=True),
    sa.Column('style_care', sa.Float(), nullable=True),
    sa.Column('color_care', sa.Float(), nullable=True),
    sa.Column('display_online', sa.Boolean(), nullable=True),
    sa.Column('freight', sa.Float(), nullable=True),
    sa.Column('picture_url', sa.String(), nullable=True),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_vendors_id'), table_name='vendors')
    op.drop_table('vendors')
    # ### end Alembic commands ###
